/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.erp111.vistas;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import org.erp111.presentadores.VentaPresentador;

/**
 *
 * @author Linkero
 */
public class VistaVenta extends javax.swing.JFrame {

    /**
     * Creates new form VistaVenta
     */
    private VentaPresentador ventaPresentador;
    
    public VistaVenta() {
        this.ventaPresentador = new VentaPresentador(this);
        initComponents();
        this.ventaPresentador.llenarListaProductos();
    }

    public JList<String> getProductosList() {
        return this.productosList;
    }

    public void setModeloListaProductos(DefaultListModel modeloListaProductos) {
        this.productosList.setModel(modeloListaProductos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventaJPanel = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVentaTable = new javax.swing.JTable();
        realizarVentaButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productosList = new javax.swing.JList<>();
        productoLabel = new javax.swing.JLabel();
        nombreProductoLabel = new javax.swing.JLabel();
        codigoLabel = new javax.swing.JLabel();
        codigoProductoLabel = new javax.swing.JLabel();
        costoUnitarioLabel = new javax.swing.JLabel();
        costoUnitarioProductoLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        cantidadTextField = new javax.swing.JTextField();
        unidadProductoLabel = new javax.swing.JLabel();
        montoLabel = new javax.swing.JLabel();
        montoProductoLabel = new javax.swing.JLabel();
        agregarListaVentaButton = new javax.swing.JButton();
        quitarProductoButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        montoVentaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tituloLabel.setText("Ventas");

        listaVentaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(listaVentaTable);

        realizarVentaButton.setText("Realizar Venta");

        cancelarButton.setText("Cancelar");

        productosList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        productosList.setToolTipText("");
        jScrollPane2.setViewportView(productosList);

        productoLabel.setText("Producto:");

        codigoLabel.setText("Codigo:");

        costoUnitarioLabel.setText("Costo unitario:");

        cantidadLabel.setText("Cantidad:");

        unidadProductoLabel.setText("unidad");

        montoLabel.setText("Monto:");

        agregarListaVentaButton.setText("Agregar a lista");

        quitarProductoButton.setText("Quitar");

        totalLabel.setText("Monto Total:");

        montoVentaLabel.setText("jLabel1");

        javax.swing.GroupLayout ventaJPanelLayout = new javax.swing.GroupLayout(ventaJPanel);
        ventaJPanel.setLayout(ventaJPanelLayout);
        ventaJPanelLayout.setHorizontalGroup(
            ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventaJPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(tituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaJPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaJPanelLayout.createSequentialGroup()
                        .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(ventaJPanelLayout.createSequentialGroup()
                                    .addComponent(realizarVentaButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cancelarButton))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ventaJPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ventaJPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(ventaJPanelLayout.createSequentialGroup()
                                                .addComponent(montoLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(montoProductoLabel))
                                            .addGroup(ventaJPanelLayout.createSequentialGroup()
                                                .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(ventaJPanelLayout.createSequentialGroup()
                                                        .addComponent(productoLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(nombreProductoLabel))
                                                    .addGroup(ventaJPanelLayout.createSequentialGroup()
                                                        .addComponent(codigoLabel)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(codigoProductoLabel))
                                                    .addGroup(ventaJPanelLayout.createSequentialGroup()
                                                        .addComponent(costoUnitarioLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(costoUnitarioProductoLabel))
                                                    .addGroup(ventaJPanelLayout.createSequentialGroup()
                                                        .addComponent(cantidadLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cantidadTextField)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(unidadProductoLabel))))
                                    .addGroup(ventaJPanelLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(agregarListaVentaButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(quitarProductoButton)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaJPanelLayout.createSequentialGroup()
                        .addComponent(totalLabel)
                        .addGap(18, 18, 18)
                        .addComponent(montoVentaLabel)
                        .addGap(27, 27, 27))))
        );
        ventaJPanelLayout.setVerticalGroup(
            ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventaJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(23, 23, 23)
                .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ventaJPanelLayout.createSequentialGroup()
                        .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productoLabel)
                            .addComponent(nombreProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigoLabel)
                            .addComponent(codigoProductoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costoUnitarioLabel)
                            .addComponent(costoUnitarioProductoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cantidadLabel)
                            .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cantidadTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(unidadProductoLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(montoLabel)
                            .addComponent(montoProductoLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarListaVentaButton)
                            .addComponent(quitarProductoButton))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(montoVentaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(ventaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(realizarVentaButton)
                    .addComponent(cancelarButton))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ventaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void llenarListaProductos(){
        this.ventaPresentador.llenarListaProductos();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarListaVentaButton;
    private javax.swing.JButton cancelarButton;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JTextField cantidadTextField;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JLabel codigoProductoLabel;
    private javax.swing.JLabel costoUnitarioLabel;
    private javax.swing.JLabel costoUnitarioProductoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listaVentaTable;
    private javax.swing.JLabel montoLabel;
    private javax.swing.JLabel montoProductoLabel;
    private javax.swing.JLabel montoVentaLabel;
    private javax.swing.JLabel nombreProductoLabel;
    private javax.swing.JLabel productoLabel;
    private javax.swing.JList<String> productosList;
    private javax.swing.JButton quitarProductoButton;
    private javax.swing.JButton realizarVentaButton;
    private javax.swing.JLabel tituloLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel unidadProductoLabel;
    private javax.swing.JPanel ventaJPanel;
    // End of variables declaration//GEN-END:variables
}
