/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.erp111.vistas.proveedores;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.erp111.presentadores.ProveedorPresentador;
import org.erp111.modelos.Proveedor;

/**
 *
 * @author lucas
 */
public class VistaProveedor extends javax.swing.JFrame {
    private ProveedorPresentador presentadorProveedores;
    
    
    
    public VistaProveedor() {
        initComponents();
        this.presentadorProveedores = new ProveedorPresentador(this);
        this.proveedorTextFieldId.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        proveedorTable = new javax.swing.JTable();
        proveedorBotonEditar = new javax.swing.JButton();
        proveedorBotonDarDeBaja = new javax.swing.JButton();
        proveedorTextFieldFiltro = new javax.swing.JTextField();
        proveedorComboBox = new javax.swing.JComboBox<>();
        proveedorBotonBuscar = new javax.swing.JButton();
        proveedorLabelNombre = new javax.swing.JLabel();
        proveedorLabelApellido = new javax.swing.JLabel();
        proveedorLabelCuit = new javax.swing.JLabel();
        proveedorLabelTelefono = new javax.swing.JLabel();
        proveedorLabelEmail = new javax.swing.JLabel();
        proveedorLabelDireccion = new javax.swing.JLabel();
        proveedorLabelCiudad = new javax.swing.JLabel();
        proveedorLabelProvincia = new javax.swing.JLabel();
        proveedorBotonGuardar = new javax.swing.JButton();
        proveedorBotonCancelarEdicion = new javax.swing.JButton();
        proveedorTextFieldNombre = new javax.swing.JTextField();
        proveedorTextFieldApellido = new javax.swing.JTextField();
        proveedorTextFieldCuit = new javax.swing.JTextField();
        proveedorTextFieldTelefono = new javax.swing.JTextField();
        proveedorTextFieldEmail = new javax.swing.JTextField();
        proveedorTextFieldDireccion = new javax.swing.JTextField();
        proveedorTextFieldCiudad = new javax.swing.JTextField();
        proveedorTextFieldProvincia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        proveedorTextFieldId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        proveedorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(proveedorTable);

        proveedorBotonEditar.setText("Editar");
        proveedorBotonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorBotonEditarApretado(evt);
            }
        });

        proveedorBotonDarDeBaja.setText("Dar de Baja");
        proveedorBotonDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorBotonDarDeBajaApretado(evt);
            }
        });

        proveedorTextFieldFiltro.setText("Escriba el proveedor que desea buscar");
        proveedorTextFieldFiltro.setToolTipText("");
        proveedorTextFieldFiltro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        proveedorTextFieldFiltro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                proveedorTextFieldFiltroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                proveedorTextFieldFiltroFocusLost(evt);
            }
        });
        proveedorTextFieldFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorTextFieldFiltroActionPerformed(evt);
            }
        });

        proveedorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nombre", "apellido", "cuit", "telefono", "email", "direccion", "localidad", "provincia" }));
        proveedorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorComboBoxActionPerformed(evt);
            }
        });

        proveedorBotonBuscar.setText("Buscar");
        proveedorBotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorBotonBuscarApretado(evt);
            }
        });

        proveedorLabelNombre.setText("Nombre:");

        proveedorLabelApellido.setText("Apellido:");

        proveedorLabelCuit.setText("CUIT:");

        proveedorLabelTelefono.setText("Teléfono:");

        proveedorLabelEmail.setText("Email:");

        proveedorLabelDireccion.setText("Dirección:");

        proveedorLabelCiudad.setText("Ciudad:");

        proveedorLabelProvincia.setText("Provincia:");

        proveedorBotonGuardar.setText("Guardar");
        proveedorBotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorBotonGuardarApretado(evt);
            }
        });

        proveedorBotonCancelarEdicion.setText("Cancelar");
        proveedorBotonCancelarEdicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorBotonCancelarEdicionApretado(evt);
            }
        });

        proveedorTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorTextFieldNombreActionPerformed(evt);
            }
        });

        proveedorTextFieldApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorTextFieldApellidoActionPerformed(evt);
            }
        });

        proveedorTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorTextFieldEmailActionPerformed(evt);
            }
        });

        proveedorTextFieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorTextFieldDireccionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("BankGothic Lt BT", 1, 18)); // NOI18N
        jLabel9.setText("Editor de Proveedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(proveedorBotonDarDeBaja)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(proveedorBotonEditar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(proveedorBotonCancelarEdicion)
                                .addGap(18, 18, 18)
                                .addComponent(proveedorBotonGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(proveedorLabelEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(proveedorLabelCuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(proveedorLabelTelefono))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(proveedorLabelNombre)
                                        .addGap(9, 9, 9)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(proveedorTextFieldCuit, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(proveedorTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(proveedorTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(proveedorTextFieldTelefono))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(proveedorLabelDireccion)
                                            .addComponent(proveedorLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(proveedorLabelCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(proveedorLabelProvincia))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(proveedorTextFieldCiudad, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(proveedorTextFieldDireccion, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(proveedorTextFieldApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(proveedorTextFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(19, 19, 19))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(proveedorTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(proveedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(proveedorTextFieldFiltro)
                        .addGap(18, 18, 18)
                        .addComponent(proveedorBotonBuscar)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedorLabelNombre)
                    .addComponent(proveedorTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedorTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedorLabelApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proveedorLabelEmail)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(proveedorTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(proveedorLabelDireccion)
                        .addComponent(proveedorTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedorLabelCiudad)
                    .addComponent(proveedorTextFieldCuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedorTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedorLabelCuit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedorLabelProvincia)
                    .addComponent(proveedorTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedorTextFieldProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedorLabelTelefono))
                .addGap(18, 18, 18)
                .addComponent(proveedorTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedorBotonGuardar)
                    .addComponent(proveedorBotonCancelarEdicion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedorTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proveedorBotonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proveedorBotonEditar)
                    .addComponent(proveedorBotonDarDeBaja))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public JTextField getIdTextField(){
        
        return proveedorTextFieldId;
    }
    
    public JTextField getNombreTextField(){
        
        return proveedorTextFieldNombre;
    }
    
    public JTextField getApellidoTextField() {
        
        return proveedorTextFieldApellido;
    }
    
    public JTextField getCuitTextField() {
        
        return proveedorTextFieldCuit;
    }
    
    public JTextField getTelefonoTextField() {
        
        return proveedorTextFieldTelefono;
    }
    
    public JTextField getEmailTextField() {
        
        return proveedorTextFieldEmail;
    }
    
    public JTextField getDireccionTextField() {
        
        return proveedorTextFieldDireccion;
    }
    
    public JTextField getCiudadTextField() {
        
        return proveedorTextFieldCiudad;
    }
    
    public JTextField getProvinciaTextField() {
        
        return proveedorTextFieldProvincia;
    }

    public JTable getProveedorTable() {
        return proveedorTable;
    }
    
    
    
    private void proveedorBotonDarDeBajaApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorBotonDarDeBajaApretado
        this.presentadorProveedores.botonDarDeBajaApretado();
    }//GEN-LAST:event_proveedorBotonDarDeBajaApretado

    private void proveedorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorComboBoxActionPerformed

    private void proveedorTextFieldFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorTextFieldFiltroActionPerformed
        
    }//GEN-LAST:event_proveedorTextFieldFiltroActionPerformed

    private void proveedorBotonEditarApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorBotonEditarApretado
        this.presentadorProveedores.botonEditarApretado();
    }//GEN-LAST:event_proveedorBotonEditarApretado

    private void proveedorBotonBuscarApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorBotonBuscarApretado
        this.presentadorProveedores.botonBuscarApretado(this.proveedorComboBox,this.proveedorTextFieldFiltro);
    }//GEN-LAST:event_proveedorBotonBuscarApretado

    private void proveedorBotonGuardarApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorBotonGuardarApretado
        this.presentadorProveedores.botonGuardarApretado();
    }//GEN-LAST:event_proveedorBotonGuardarApretado

    private void proveedorBotonCancelarEdicionApretado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorBotonCancelarEdicionApretado
        this.presentadorProveedores.botonCancelarEdicionApretado();
    }//GEN-LAST:event_proveedorBotonCancelarEdicionApretado

    private void proveedorTextFieldFiltroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proveedorTextFieldFiltroFocusGained
       proveedorTextFieldFiltro.setText("");
    }//GEN-LAST:event_proveedorTextFieldFiltroFocusGained

    private void proveedorTextFieldFiltroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_proveedorTextFieldFiltroFocusLost
        if(proveedorTextFieldFiltro.getText().equals("")){
            proveedorTextFieldFiltro.setText("Escriba el proveedor que desea buscar");
        }
    }//GEN-LAST:event_proveedorTextFieldFiltroFocusLost

    private void proveedorTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorTextFieldEmailActionPerformed

    private void proveedorTextFieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorTextFieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorTextFieldDireccionActionPerformed

    private void proveedorTextFieldApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorTextFieldApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorTextFieldApellidoActionPerformed

    private void proveedorTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorTextFieldNombreActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton proveedorBotonBuscar;
    private javax.swing.JButton proveedorBotonCancelarEdicion;
    private javax.swing.JButton proveedorBotonDarDeBaja;
    private javax.swing.JButton proveedorBotonEditar;
    private javax.swing.JButton proveedorBotonGuardar;
    private javax.swing.JComboBox<String> proveedorComboBox;
    private javax.swing.JLabel proveedorLabelApellido;
    private javax.swing.JLabel proveedorLabelCiudad;
    private javax.swing.JLabel proveedorLabelCuit;
    private javax.swing.JLabel proveedorLabelDireccion;
    private javax.swing.JLabel proveedorLabelEmail;
    private javax.swing.JLabel proveedorLabelNombre;
    private javax.swing.JLabel proveedorLabelProvincia;
    private javax.swing.JLabel proveedorLabelTelefono;
    private javax.swing.JTable proveedorTable;
    private javax.swing.JTextField proveedorTextFieldApellido;
    private javax.swing.JTextField proveedorTextFieldCiudad;
    private javax.swing.JTextField proveedorTextFieldCuit;
    private javax.swing.JTextField proveedorTextFieldDireccion;
    private javax.swing.JTextField proveedorTextFieldEmail;
    private javax.swing.JTextField proveedorTextFieldFiltro;
    private javax.swing.JTextField proveedorTextFieldId;
    private javax.swing.JTextField proveedorTextFieldNombre;
    private javax.swing.JTextField proveedorTextFieldProvincia;
    private javax.swing.JTextField proveedorTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
