package org.erp111.modelos;
// Generated 08/10/2018 14:27:19 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codigoCliente;
     private String nombreApellido;
     private String telefono;
     private String direccion;
     private String localidad;
     private String cuil;
     private Set ventas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nombreApellido, String telefono, String direccion, String localidad, String cuil) {
        this.nombreApellido = nombreApellido;
        this.telefono = telefono;
        this.direccion = direccion;
        this.localidad = localidad;
        this.cuil = cuil;
    }
    public Cliente(String nombreApellido, String telefono, String direccion, String localidad, String cuil, Set ventas) {
       this.nombreApellido = nombreApellido;
       this.telefono = telefono;
       this.direccion = direccion;
       this.localidad = localidad;
       this.cuil = cuil;
       this.ventas = ventas;
    }
   
    public Integer getCodigoCliente() {
        return this.codigoCliente;
    }
    
    public void setCodigoCliente(Integer codigoCliente) {
        this.codigoCliente = codigoCliente;
    }
    public String getNombreApellido() {
        return this.nombreApellido;
    }
    
    public void setNombreApellido(String nombreApellido) {
        this.nombreApellido = nombreApellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getCuil() {
        return this.cuil;
    }
    
    public void setCuil(String cuil) {
        this.cuil = cuil;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


