package org.erp111.modelos;
<<<<<<< HEAD
// Generated 25/09/2018 20:53:19 by Hibernate Tools 4.3.1
=======
// Generated 25/09/2018 14:25:04 by Hibernate Tools 4.3.1
>>>>>>> ea83eba1c5075aaf20137d56d6815ba56d7b0f1d



/**
 * DetalleCompra generated by hbm2java
 */
public class DetalleCompra  implements java.io.Serializable {


     private Integer codigoDetalleCompra;
     private Compra compra;
     private Producto producto;
     private double cantidad;
     private double precioUnitario;

    public DetalleCompra() {
    }

    public DetalleCompra(Compra compra, Producto producto, double cantidad, double precioUnitario) {
       this.compra = compra;
       this.producto = producto;
       this.cantidad = cantidad;
       this.precioUnitario = precioUnitario;
    }
   
    public Integer getCodigoDetalleCompra() {
        return this.codigoDetalleCompra;
    }
    
    public void setCodigoDetalleCompra(Integer codigoDetalleCompra) {
        this.codigoDetalleCompra = codigoDetalleCompra;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(double cantidad) {
        this.cantidad = cantidad;
    }
    public double getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }




}


