package org.erp111.modelos;
// Generated 24/10/2018 16:01:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer codigoProveedor;
     private String nombre;
     private String apellido;
     private String cuit;
     private String telefono;
     private String email;
     private String direccion;
     private String localidad;
     private String provincia;
     
     @Enumerated(EnumType.STRING)
     private EstadosProveedor estado = EstadosProveedor.ACTIVO;
     
     private Set compras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombre, String apellido, String cuit, String telefono, String email, String direccion, String localidad, String provincia) {
        this.nombre = nombre;
        this.apellido = apellido;
        this.cuit = cuit;
        this.telefono = telefono;
        this.email = email;
        this.direccion = direccion;
        this.localidad = localidad;
        this.provincia = provincia;
    }
    public Proveedor(String nombre, String apellido, String cuit, String telefono, String email, String direccion, String localidad, String provincia, EstadosProveedor estado, Set compras) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.cuit = cuit;
       this.telefono = telefono;
       this.email = email;
       this.direccion = direccion;
       this.localidad = localidad;
       this.provincia = provincia;
       this.estado = estado;
       this.compras = compras;
    }
   
    public Integer getCodigoProveedor() {
        return this.codigoProveedor;
    }
    
    public void setCodigoProveedor(Integer codigoProveedor) {
        this.codigoProveedor = codigoProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public EstadosProveedor getEstado() {
        return this.estado;
    }
    
    public void setEstado(EstadosProveedor estado) {
        this.estado = estado;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }
    
    public boolean estaDadoDeBaja() {
        if(getEstado() != null){
            return getEstado().equals("baja");
        }
        else {
            return false;
        }
    }

}


