package org.erp111.modelos;
// Generated 17/09/2018 15:42:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer codigoProveedor;
     private String nombreApellido;
     private String cuit;
     private String telefono;
     private String email;
     private String direccion;
     private String localidad;
     private String provincia;
     private String rubro;
     private Set compras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(String nombreApellido, String cuit, String telefono, String email, String direccion, String localidad, String provincia, String rubro) {
        this.nombreApellido = nombreApellido;
        this.cuit = cuit;
        this.telefono = telefono;
        this.email = email;
        this.direccion = direccion;
        this.localidad = localidad;
        this.provincia = provincia;
        this.rubro = rubro;
    }
    public Proveedor(String nombreApellido, String cuit, String telefono, String email, String direccion, String localidad, String provincia, String rubro, Set compras) {
       this.nombreApellido = nombreApellido;
       this.cuit = cuit;
       this.telefono = telefono;
       this.email = email;
       this.direccion = direccion;
       this.localidad = localidad;
       this.provincia = provincia;
       this.rubro = rubro;
       this.compras = compras;
    }
   
    public Integer getCodigoProveedor() {
        return this.codigoProveedor;
    }
    
    public void setCodigoProveedor(Integer codigoProveedor) {
        this.codigoProveedor = codigoProveedor;
    }
    public String getNombreApellido() {
        return this.nombreApellido;
    }
    
    public void setNombreApellido(String nombreApellido) {
        this.nombreApellido = nombreApellido;
    }
    public String getCuit() {
        return this.cuit;
    }
    
    public void setCuit(String cuit) {
        this.cuit = cuit;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getRubro() {
        return this.rubro;
    }
    
    public void setRubro(String rubro) {
        this.rubro = rubro;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


