package org.erp111.modelos;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer codigoVenta;
     private Cliente cliente;
     private double monto;
     private Date fecha;
     private double descuento;
     private Set detalleVentas = new HashSet(0);

    public Venta() {
    }

	
    public Venta(Cliente cliente, double monto, Date fecha, double descuento) {
        this.cliente = cliente;
        this.monto = monto;
        this.fecha = fecha;
        this.descuento = descuento;
    }
    public Venta(Cliente cliente, double monto, Date fecha, double descuento, Set detalleVentas) {
       this.cliente = cliente;
       this.monto = monto;
       this.fecha = fecha;
       this.descuento = descuento;
       this.detalleVentas = detalleVentas;
    }
   
    public Integer getCodigoVenta() {
        return this.codigoVenta;
    }
    
    public void setCodigoVenta(Integer codigoVenta) {
        this.codigoVenta = codigoVenta;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public double getMonto() {
        return this.monto;
    }
    
    public void setMonto(double monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(double descuento) {
        this.descuento = descuento;
    }
    public Set getDetalleVentas() {
        return this.detalleVentas;
    }
    
    public void setDetalleVentas(Set detalleVentas) {
        this.detalleVentas = detalleVentas;
    }




}


